Allow setting custom headers on Client
sanity-io/client-go pull request #5
Opened 2021-08-31 13:03 UTC by j33ty

Also fixes a bug where `Accept` header was being set twice.

2021-09-01 05:40 UTC, judofyr approved these changes

2021-09-01 14:21 UTC, atombender requested changes
Nice!

2021-09-01 14:21 UTC, atombender commented on client.go
> +	return func(c *Client) { c.customHeaders = headers }
Would be a good idea to copy here. Not copying could lead to race conditions if the caller isn't aware that it's used as is. Another option is to accept key-value pairs:

```
func WithHTTPHeader(key, value string) Option
```

Internally, I think we should leverage `http.Header`.

2021-09-10 09:56 UTC, atombender approved these changes

2021-09-10 09:58 UTC, merged